version: "3.7"
services:
#  ============= MYSQL DB =============
  db:
    container_name: task-db
    platform: linux/x86_64
    image: mysql:8.0.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS `task`;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  #============= TASK BACKEND =============
  codex-task:
    container_name: codex
    image: nikitarizh/codex-testtask
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=task-db
      - DB_NAME=task
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - EMAIL_USER=codex.testtask@gmail.com
      - EMAIL_PASSWORD=qennix-deqqEg-roqqa4
    depends_on:
      - "db"
    restart: always
